[project]
name = "db-project-tokopee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mysql-connector-python>=9.5.0",
    "pandas>=2.3.3",
]
