[project]
name = "db-project-tokopee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mnemonic>=0.21",
    "mysql-connector-python>=9.5.0",
    "pydantic>=2.12.4",
]
